# Generated by Django 5.2.7 on 2025-10-18 20:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the online consultation')),
                ('diagnosis', models.TextField(help_text='Medical diagnosis')),
                ('symptoms', models.TextField(blank=True, help_text='Observed symptoms')),
                ('treatment', models.TextField(help_text='Treatment provided or recommended')),
                ('prescription', models.TextField(blank=True, help_text='Medications prescribed')),
                ('follow_up_required', models.BooleanField(default=False, help_text='Whether a follow-up consultation is needed')),
                ('follow_up_date', models.DateField(blank=True, help_text='Scheduled follow-up date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Pet weight in kg at time of visit', max_digits=6, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in Celsius', max_digits=4, null=True)),
                ('test_results', models.FileField(blank=True, help_text='Lab test results or medical documents', null=True, upload_to='medical_records/tests/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Associated appointment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='appointments.appointment')),
                ('pet', models.ForeignKey(help_text='Pet this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.petprofile')),
                ('veterinarian', models.ForeignKey(blank=True, help_text='Veterinarian who created this record', limit_choices_to={'role': 'VETERINARIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-visit_date', '-created_at'],
                'indexes': [models.Index(fields=['pet', 'visit_date'], name='medical_rec_pet_id_523875_idx'), models.Index(fields=['veterinarian', 'visit_date'], name='medical_rec_veterin_50426c_idx'), models.Index(fields=['appointment'], name='medical_rec_appoint_900109_idx')],
            },
        ),
    ]
