# Generated by Django 5.2.7 on 2025-10-14 21:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccination',
            old_name='date_given',
            new_name='date_administered',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
