# Generated by Django 5.2.7 on 2025-10-14 21:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AddField(
            model_name='petprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
