# Generated by Django 5.2.7 on 2025-10-17 22:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Appointment date')),
                ('time', models.TimeField(blank=True, help_text='Appointment time (optional until confirmed)', null=True)),
                ('reason', models.TextField(help_text='Reason for the appointment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Pet owner requesting the appointment', limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(help_text='Pet for the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.petprofile')),
                ('veterinarian', models.ForeignKey(help_text='Veterinarian assigned to the appointment', limit_choices_to={'role': 'VETERINARIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='vet_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='Diagnosis from the consultation')),
                ('symptoms', models.TextField(blank=True, help_text='Symptoms observed during consultation')),
                ('notes', models.TextField(help_text='Detailed consultation notes')),
                ('prescription', models.TextField(blank=True, help_text='Prescribed medications or treatments')),
                ('follow_up_required', models.BooleanField(default=False, help_text='Whether a follow-up appointment is needed')),
                ('follow_up_date', models.DateField(blank=True, help_text='Recommended follow-up date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(help_text='Associated appointment', on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.appointment')),
                ('veterinarian', models.ForeignKey(help_text='Veterinarian who conducted the consultation', limit_choices_to={'role': 'VETERINARIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'status'], name='appointment_date_32174a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'date'], name='appointment_client__ab13e2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['veterinarian', 'date'], name='appointment_veterin_078b64_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['veterinarian', 'created_at'], name='appointment_veterin_a2e668_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['appointment'], name='appointment_appoint_42da83_idx'),
        ),
    ]
