# Generated by Django 5.2.7 on 2025-10-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='scheduled_date',
            new_name='appointment_date',
        ),
    ]
