# Generated by Django 5.2.7 on 2025-10-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('VETERINARIAN', 'veterinarian'), ('CLIENT', 'client')], default='CLIENT', max_length=12),
        ),
    ]
