# Generated by Django 5.2.7 on 2025-10-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='following',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_vet',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('veterinarian', 'Veterinarian'), ('client', 'Client')], default=2, max_length=12),
            preserve_default=False,
        ),
    ]
