# Generated by Django 5.2.7 on 2025-10-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_ownerprofile_clientprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('vet', 'Vet'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
